### ISSUE TITLE
CodeGen issue

### ISSUE THREAD

**Issue by Bezarius** [Cysharp/MasterMemory#47]
Hi! I found minor issue. That issue not problem for me, but I think that report can be helpfull for someone.

```
Fail in console app running on MessagepackCompiler.RunAsync
MessagePackCompiler.CodeAnalysis.MessagePackGeneratorResolveFailedException: can't find matched constructor. type:global::_Game.DataModel.Stats
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectObject(INamedTypeSymbol type) in d:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 541
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectCore(ITypeSymbol typeSymbol) in d:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 384
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectObject(INamedTypeSymbol type) in d:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 589
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectCore(ITypeSymbol typeSymbol) in d:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 384
   at MessagePackCompiler.CodeAnalysis.TypeCollector.Collect() in d:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 319
   at MessagePackCompiler.CodeGenerator.GenerateFileAsync(String input, String output, String conditionalSymbol, String resolverName, String namespace, Boolean useMapMode, String multipleIfDirectiveOutputSymbols) in d:\a\1\s\src\MessagePack.GeneratorCore\CodeGenerator.cs:line 58
   at MessagePack.Generator.MessagepackCompiler.RunAsync(String input, String output, String conditionalSymbol, String resolverName, String namespace, Boolean useMapMode, String multipleIfDirectiveOutputSymbols) in d:\a\1\s\src\MessagePack.Generator\MessagepackCompiler.cs:line 30
   at ConsoleAppFramework.ConsoleAppEngine.RunCore(ConsoleAppContext ctx, Type type, MethodInfo methodInfo, String[] args, Int32 argsOffset)
```

```csharp
    [MessagePackObject(true)]
    public class Stats
    {
        public int Str { get; }
        public int Con { get; }
        public int Dex { get; }
        public int Int { get; }
        public int Men { get; }
        public int Wit { get; }
        public int Cha { get; }
        public int Lck { get; }

        public Stats(int str, int con, int dex, int intelligence, int men, int wit, int cha, int lck)
        {
            Str = str;
            Con = con;
            Dex = dex;
            Int = intelligence; // <== Problem here. Compiler doesn't like 'Int' name 
            Men = men;
            Wit = wit;
            Cha = cha;
            Lck = lck;
        }
    } 
```

**Comment by neuecc** [comment]
this is MessagePack restriction, constructor name should same as property name.
